jobs:
- job: tests
  trigger: pull_request
  metadata:
    targets:
    - fedora-all
actions:
  create-archive:
  - pwd
  - find -type f
  - bash -c "set -x; gem build --debug *.gemspec"
  - bash -c "ls *.gem"
  fix-spec-file:
  - 'true'
