jobs:
- job: tests
  trigger: pull_request
  metadata:
    targets:
    - fedora-all
actions:
  create-archive:
  - gem build
  - bash -c "ls *.gem"
  get-current-version:
  - bash -c "grep -i version *.gemspec | cut -d'\"' -f2"
